<?php


 function autoload_6297f270070d0097e9b0e2c30d0167e9($class)
{
    $classes = array(
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\Job_SSP' => __DIR__ .'/Job_SSP.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetFolderPath' => __DIR__ .'/GetFolderPath.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetFolderPathResponse' => __DIR__ .'/GetFolderPathResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResults' => __DIR__ .'/GetOutputResults.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultsResponse' => __DIR__ .'/GetOutputResultsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\AddFileToOutputResults' => __DIR__ .'/AddFileToOutputResults.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\ArrayOfProperty' => __DIR__ .'/ArrayOfProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\Property' => __DIR__ .'/Property.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\AddFileToOutputResultsResponse' => __DIR__ .'/AddFileToOutputResultsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\AddFilesToOutputResults' => __DIR__ .'/AddFilesToOutputResults.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\AddFilesToOutputResultsResponse' => __DIR__ .'/AddFilesToOutputResultsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\DeleteOutputResults' => __DIR__ .'/DeleteOutputResults.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\DeleteOutputResultsResponse' => __DIR__ .'/DeleteOutputResultsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultsInfo' => __DIR__ .'/GetOutputResultsInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultsInfoResponse' => __DIR__ .'/GetOutputResultsInfoResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\ArrayOfOutputResult' => __DIR__ .'/ArrayOfOutputResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\OutputResult' => __DIR__ .'/OutputResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultBinaryFileStream' => __DIR__ .'/GetOutputResultBinaryFileStream.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultBinaryFileStreamResponse' => __DIR__ .'/GetOutputResultBinaryFileStreamResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultBinaryFileStreamChunk' => __DIR__ .'/GetOutputResultBinaryFileStreamChunk.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultBinaryFileStreamChunkResponse' => __DIR__ .'/GetOutputResultBinaryFileStreamChunkResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultBinaryFileStreamSize' => __DIR__ .'/GetOutputResultBinaryFileStreamSize.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultBinaryFileStreamSizeResponse' => __DIR__ .'/GetOutputResultBinaryFileStreamSizeResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultDownloadURL' => __DIR__ .'/GetOutputResultDownloadURL.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetOutputResultDownloadURLResponse' => __DIR__ .'/GetOutputResultDownloadURLResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetProperty' => __DIR__ .'/GetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetPropertyResponse' => __DIR__ .'/GetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetProperties' => __DIR__ .'/GetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetPropertiesResponse' => __DIR__ .'/GetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetAllProperties' => __DIR__ .'/GetAllProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetAllPropertiesResponse' => __DIR__ .'/GetAllPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetDataSet' => __DIR__ .'/GetDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetDataSetResponse' => __DIR__ .'/GetDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetDataSetResult' => __DIR__ .'/GetDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetXMPTblDataSet' => __DIR__ .'/GetXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetXMPTblDataSetResponse' => __DIR__ .'/GetXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\XMPTblDataSet' => __DIR__ .'/XMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\ArrayOfXMPTbl' => __DIR__ .'/ArrayOfXMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\XMPTbl' => __DIR__ .'/XMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\ArrayOfXMPTblColumn' => __DIR__ .'/ArrayOfXMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\XMPTblColumn' => __DIR__ .'/XMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\ArrayOfXMPTblRow' => __DIR__ .'/ArrayOfXMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\XMPTblRow' => __DIR__ .'/XMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\ArrayOfXMPRowField' => __DIR__ .'/ArrayOfXMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\XMPRowField' => __DIR__ .'/XMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\SetProperty' => __DIR__ .'/SetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\SetPropertyResponse' => __DIR__ .'/SetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\SetProperties' => __DIR__ .'/SetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\SetPropertiesResponse' => __DIR__ .'/SetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\Abort' => __DIR__ .'/Abort.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\AbortResponse' => __DIR__ .'/AbortResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\ReQueue' => __DIR__ .'/ReQueue.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\ReQueueResponse' => __DIR__ .'/ReQueueResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\Delete' => __DIR__ .'/Delete.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\DeleteResponse' => __DIR__ .'/DeleteResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetStatus' => __DIR__ .'/GetStatus.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetStatusResponse' => __DIR__ .'/GetStatusResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\SetProgressStatus' => __DIR__ .'/SetProgressStatus.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\SetProgressStatusResponse' => __DIR__ .'/SetProgressStatusResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetTicket' => __DIR__ .'/GetTicket.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetTicketResponse' => __DIR__ .'/GetTicketResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessages' => __DIR__ .'/GetMessages.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessagesResponse' => __DIR__ .'/GetMessagesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessagesDataSet' => __DIR__ .'/GetMessagesDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessagesDataSetResponse' => __DIR__ .'/GetMessagesDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessagesDataSetResult' => __DIR__ .'/GetMessagesDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessagesXMPTblDataSet' => __DIR__ .'/GetMessagesXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessagesXMPTblDataSetResponse' => __DIR__ .'/GetMessagesXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessagesNum' => __DIR__ .'/GetMessagesNum.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessagesNumResponse' => __DIR__ .'/GetMessagesNumResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessagesHighestSeverity' => __DIR__ .'/GetMessagesHighestSeverity.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetMessagesHighestSeverityResponse' => __DIR__ .'/GetMessagesHighestSeverityResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\DeleteMessages' => __DIR__ .'/DeleteMessages.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\DeleteMessagesResponse' => __DIR__ .'/DeleteMessagesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetCampaignShortcutInfo' => __DIR__ .'/GetCampaignShortcutInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetCampaignShortcutInfoResponse' => __DIR__ .'/GetCampaignShortcutInfoResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\CampaignShortcutInfo' => __DIR__ .'/CampaignShortcutInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetTouchPoint' => __DIR__ .'/GetTouchPoint.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\GetTouchPointResponse' => __DIR__ .'/GetTouchPointResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\SetTouchPoint' => __DIR__ .'/SetTouchPoint.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\SetTouchPointResponse' => __DIR__ .'/SetTouchPointResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\IsExist' => __DIR__ .'/IsExist.php',
        'XMPieWsdlClient\XMPie\uProduce\v_11_2_2\ProductionServices\Job_SSP\IsExistResponse' => __DIR__ .'/IsExistResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_6297f270070d0097e9b0e2c30d0167e9');

// Do nothing. The rest is just leftovers from the code generation.
{
}
