<?php


 function autoload_cc3464a49cdf8c73b43b05e2989fa433($class)
{
    $classes = array(
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\DataSource_SSP' => __DIR__ .'/DataSource_SSP.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\CreateNew' => __DIR__ .'/CreateNew.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ArrayOfProperty' => __DIR__ .'/ArrayOfProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\Property' => __DIR__ .'/Property.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\CreateNewResponse' => __DIR__ .'/CreateNewResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\CreateNewFromZip' => __DIR__ .'/CreateNewFromZip.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\CreateNewFromZipResponse' => __DIR__ .'/CreateNewFromZipResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\Replace' => __DIR__ .'/Replace.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\Connection' => __DIR__ .'/Connection.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ReplaceResponse' => __DIR__ .'/ReplaceResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ReplaceFromZip' => __DIR__ .'/ReplaceFromZip.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ReplaceFromZipResponse' => __DIR__ .'/ReplaceFromZipResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\Delete' => __DIR__ .'/Delete.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\DeleteResponse' => __DIR__ .'/DeleteResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetPlan' => __DIR__ .'/GetPlan.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetPlanResponse' => __DIR__ .'/GetPlanResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetCampaign' => __DIR__ .'/GetCampaign.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetCampaignResponse' => __DIR__ .'/GetCampaignResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetFolderPath' => __DIR__ .'/GetFolderPath.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetFolderPathResponse' => __DIR__ .'/GetFolderPathResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetName' => __DIR__ .'/GetName.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetNameResponse' => __DIR__ .'/GetNameResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetProperty' => __DIR__ .'/GetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetPropertyResponse' => __DIR__ .'/GetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetProperties' => __DIR__ .'/GetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetPropertiesResponse' => __DIR__ .'/GetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetAllProperties' => __DIR__ .'/GetAllProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetAllPropertiesResponse' => __DIR__ .'/GetAllPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetDataSet' => __DIR__ .'/GetDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetDataSetResponse' => __DIR__ .'/GetDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetDataSetResult' => __DIR__ .'/GetDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetXMPTblDataSet' => __DIR__ .'/GetXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetXMPTblDataSetResponse' => __DIR__ .'/GetXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\XMPTblDataSet' => __DIR__ .'/XMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ArrayOfXMPTbl' => __DIR__ .'/ArrayOfXMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\XMPTbl' => __DIR__ .'/XMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ArrayOfXMPTblColumn' => __DIR__ .'/ArrayOfXMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\XMPTblColumn' => __DIR__ .'/XMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ArrayOfXMPTblRow' => __DIR__ .'/ArrayOfXMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\XMPTblRow' => __DIR__ .'/XMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ArrayOfXMPRowField' => __DIR__ .'/ArrayOfXMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\XMPRowField' => __DIR__ .'/XMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\SetProperty' => __DIR__ .'/SetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\SetPropertyResponse' => __DIR__ .'/SetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\SetProperties' => __DIR__ .'/SetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\SetPropertiesResponse' => __DIR__ .'/SetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetConnectionInfo' => __DIR__ .'/GetConnectionInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetConnectionInfoResponse' => __DIR__ .'/GetConnectionInfoResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\IsDownloadable' => __DIR__ .'/IsDownloadable.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\IsDownloadableResponse' => __DIR__ .'/IsDownloadableResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetPath' => __DIR__ .'/GetPath.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetPathResponse' => __DIR__ .'/GetPathResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetBinaryFileStream' => __DIR__ .'/GetBinaryFileStream.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetBinaryFileStreamResponse' => __DIR__ .'/GetBinaryFileStreamResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetBinaryFileStreamChunk' => __DIR__ .'/GetBinaryFileStreamChunk.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetBinaryFileStreamChunkResponse' => __DIR__ .'/GetBinaryFileStreamChunkResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetBinaryFileStreamSize' => __DIR__ .'/GetBinaryFileStreamSize.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetBinaryFileStreamSizeResponse' => __DIR__ .'/GetBinaryFileStreamSizeResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetDownloadURL' => __DIR__ .'/GetDownloadURL.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetDownloadURLResponse' => __DIR__ .'/GetDownloadURLResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetID' => __DIR__ .'/GetID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetIDResponse' => __DIR__ .'/GetIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\IsExist' => __DIR__ .'/IsExist.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\IsExistResponse' => __DIR__ .'/IsExistResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\HostTables' => __DIR__ .'/HostTables.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\HostTablesResponse' => __DIR__ .'/HostTablesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\HostAllTables' => __DIR__ .'/HostAllTables.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\HostAllTablesResponse' => __DIR__ .'/HostAllTablesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetTablesNamesForPort' => __DIR__ .'/GetTablesNamesForPort.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetTablesNamesForPortResponse' => __DIR__ .'/GetTablesNamesForPortResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetTablesNames' => __DIR__ .'/GetTablesNames.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetTablesNamesResponse' => __DIR__ .'/GetTablesNamesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\IsPrimaryTable' => __DIR__ .'/IsPrimaryTable.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\IsPrimaryTableResponse' => __DIR__ .'/IsPrimaryTableResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\IsPrimaryFieldUnique' => __DIR__ .'/IsPrimaryFieldUnique.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\IsPrimaryFieldUniqueResponse' => __DIR__ .'/IsPrimaryFieldUniqueResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ConvertToPrimaryTable' => __DIR__ .'/ConvertToPrimaryTable.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ConvertToPrimaryTableResponse' => __DIR__ .'/ConvertToPrimaryTableResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\Report' => __DIR__ .'/Report.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ArrayOfReportMessage' => __DIR__ .'/ArrayOfReportMessage.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ReportMessage' => __DIR__ .'/ReportMessage.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetFieldNames' => __DIR__ .'/GetFieldNames.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetFieldNamesResponse' => __DIR__ .'/GetFieldNamesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ExportHostedTables' => __DIR__ .'/ExportHostedTables.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ExportHostedTablesResponse' => __DIR__ .'/ExportHostedTablesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ExportAllHostedTables' => __DIR__ .'/ExportAllHostedTables.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ExportAllHostedTablesResponse' => __DIR__ .'/ExportAllHostedTablesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\SetSettings' => __DIR__ .'/SetSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\ArrayOfSetting' => __DIR__ .'/ArrayOfSetting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\Setting' => __DIR__ .'/Setting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\SetSettingsResponse' => __DIR__ .'/SetSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetSettings' => __DIR__ .'/GetSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetSettingsResponse' => __DIR__ .'/GetSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\DeleteSettings' => __DIR__ .'/DeleteSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\DeleteSettingsResponse' => __DIR__ .'/DeleteSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetRecipientTableID' => __DIR__ .'/GetRecipientTableID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetRecipientTableIDResponse' => __DIR__ .'/GetRecipientTableIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetRecipientTables' => __DIR__ .'/GetRecipientTables.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetRecipientTablesResponse' => __DIR__ .'/GetRecipientTablesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetRecipientTablesDataSet' => __DIR__ .'/GetRecipientTablesDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetRecipientTablesDataSetResponse' => __DIR__ .'/GetRecipientTablesDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetRecipientTablesDataSetResult' => __DIR__ .'/GetRecipientTablesDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetFirstRecipientFields' => __DIR__ .'/GetFirstRecipientFields.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\DataSource_SSP\GetFirstRecipientFieldsResponse' => __DIR__ .'/GetFirstRecipientFieldsResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_cc3464a49cdf8c73b43b05e2989fa433');

// Do nothing. The rest is just leftovers from the code generation.
{
}
