<?php


function autoload_aed2a617c0d9bba4e1550d7020676459($class)
{
    $classes = array(
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\DeliveryProvider_SSP' => __DIR__ . '/DeliveryProvider_SSP.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\CreateNew' => __DIR__ . '/CreateNew.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ArrayOfEmailProviderParameter' => __DIR__ . '/ArrayOfEmailProviderParameter.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\EmailProviderParameter' => __DIR__ . '/EmailProviderParameter.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ArrayOfProperty' => __DIR__ . '/ArrayOfProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\Property' => __DIR__ . '/Property.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\CreateNewResponse' => __DIR__ . '/CreateNewResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\Replace' => __DIR__ . '/Replace.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ReplaceResponse' => __DIR__ . '/ReplaceResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\Delete' => __DIR__ . '/Delete.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\DeleteResponse' => __DIR__ . '/DeleteResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetCustomer' => __DIR__ . '/GetCustomer.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetCustomerResponse' => __DIR__ . '/GetCustomerResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetProperty' => __DIR__ . '/GetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetPropertyResponse' => __DIR__ . '/GetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetProperties' => __DIR__ . '/GetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ArrayOfString' => __DIR__ . '/ArrayOfString.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetPropertiesResponse' => __DIR__ . '/GetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetAllProperties' => __DIR__ . '/GetAllProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetAllPropertiesResponse' => __DIR__ . '/GetAllPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDataSet' => __DIR__ . '/GetDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDataSetResponse' => __DIR__ . '/GetDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDataSetResult' => __DIR__ . '/GetDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetXMPTblDataSet' => __DIR__ . '/GetXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetXMPTblDataSetResponse' => __DIR__ . '/GetXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\XMPTblDataSet' => __DIR__ . '/XMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ArrayOfXMPTbl' => __DIR__ . '/ArrayOfXMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\XMPTbl' => __DIR__ . '/XMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ArrayOfXMPTblColumn' => __DIR__ . '/ArrayOfXMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\XMPTblColumn' => __DIR__ . '/XMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ArrayOfXMPTblRow' => __DIR__ . '/ArrayOfXMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\XMPTblRow' => __DIR__ . '/XMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ArrayOfXMPRowField' => __DIR__ . '/ArrayOfXMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\XMPRowField' => __DIR__ . '/XMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SetProperty' => __DIR__ . '/SetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SetPropertyResponse' => __DIR__ . '/SetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SetProperties' => __DIR__ . '/SetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SetPropertiesResponse' => __DIR__ . '/SetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderParameters' => __DIR__ . '/GetDeliveryProviderParameters.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderParametersResponse' => __DIR__ . '/GetDeliveryProviderParametersResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SetDeliveryProviderParameters' => __DIR__ . '/SetDeliveryProviderParameters.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SetDeliveryProviderParametersResponse' => __DIR__ . '/SetDeliveryProviderParametersResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetID' => __DIR__ . '/GetID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetIDResponse' => __DIR__ . '/GetIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderInfo' => __DIR__ . '/GetDeliveryProviderInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderInfoResponse' => __DIR__ . '/GetDeliveryProviderInfoResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\EmailProviderInfo' => __DIR__ . '/EmailProviderInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderTypes' => __DIR__ . '/GetDeliveryProviderTypes.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderTypesResponse' => __DIR__ . '/GetDeliveryProviderTypesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderTypesResult' => __DIR__ . '/GetDeliveryProviderTypesResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderTypesXMPTblDataSet' => __DIR__ . '/GetDeliveryProviderTypesXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderTypesXMPTblDataSetResponse' => __DIR__ . '/GetDeliveryProviderTypesXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderType' => __DIR__ . '/GetDeliveryProviderType.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderTypeResponse' => __DIR__ . '/GetDeliveryProviderTypeResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderTypeResult' => __DIR__ . '/GetDeliveryProviderTypeResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderTypeXMPTblDataSet' => __DIR__ . '/GetDeliveryProviderTypeXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetDeliveryProviderTypeXMPTblDataSetResponse' => __DIR__ . '/GetDeliveryProviderTypeXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SendMail' => __DIR__ . '/SendMail.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\EmailHeaderInfo' => __DIR__ . '/EmailHeaderInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ArrayOfEmailAddress' => __DIR__ . '/ArrayOfEmailAddress.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\EmailAddress' => __DIR__ . '/EmailAddress.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ArrayOfEmailBodyInfo' => __DIR__ . '/ArrayOfEmailBodyInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\EmailBodyInfo' => __DIR__ . '/EmailBodyInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\EmailBodyOptions' => __DIR__ . '/EmailBodyOptions.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\URLInfo' => __DIR__ . '/URLInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SendMailResponse' => __DIR__ . '/SendMailResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SendEmailResult' => __DIR__ . '/SendEmailResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SendMailByProviderInfo' => __DIR__ . '/SendMailByProviderInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SendMailByProviderInfoResponse' => __DIR__ . '/SendMailByProviderInfoResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ProviderCustomActionByProviderInfo' => __DIR__ . '/ProviderCustomActionByProviderInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ProviderCustomActionByProviderInfoResponse' => __DIR__ . '/ProviderCustomActionByProviderInfoResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ProviderCustomAction' => __DIR__ . '/ProviderCustomAction.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ProviderCustomActionResponse' => __DIR__ . '/ProviderCustomActionResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\IsExist' => __DIR__ . '/IsExist.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\IsExistResponse' => __DIR__ . '/IsExistResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetStatus' => __DIR__ . '/GetStatus.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetStatusResponse' => __DIR__ . '/GetStatusResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\StatusInfo' => __DIR__ . '/StatusInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SetSettings' => __DIR__ . '/SetSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\ArrayOfSetting' => __DIR__ . '/ArrayOfSetting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\Setting' => __DIR__ . '/Setting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\SetSettingsResponse' => __DIR__ . '/SetSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetSettings' => __DIR__ . '/GetSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\GetSettingsResponse' => __DIR__ . '/GetSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\DeleteSettings' => __DIR__ . '/DeleteSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\DeliveryProvider_SSP\DeleteSettingsResponse' => __DIR__ . '/DeleteSettingsResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    }
}

spl_autoload_register('autoload_aed2a617c0d9bba4e1550d7020676459');

// Do nothing. The rest is just leftovers from the code generation.
{
}
