<?php


 function autoload_80370c70de3a1829762360b8eedb3d52($class)
{
    $classes = array(
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\AssetSource_SSP' => __DIR__ .'/AssetSource_SSP.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\CreateNew' => __DIR__ .'/CreateNew.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\ArrayOfProperty' => __DIR__ .'/ArrayOfProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\Property' => __DIR__ .'/Property.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\CreateNewResponse' => __DIR__ .'/CreateNewResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\CreateNewEx' => __DIR__ .'/CreateNewEx.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\ArrayOfAssetSourceParameter' => __DIR__ .'/ArrayOfAssetSourceParameter.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\AssetSourceParameter' => __DIR__ .'/AssetSourceParameter.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\CreateNewExResponse' => __DIR__ .'/CreateNewExResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\Delete' => __DIR__ .'/Delete.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\DeleteResponse' => __DIR__ .'/DeleteResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetCampaign' => __DIR__ .'/GetCampaign.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetCampaignResponse' => __DIR__ .'/GetCampaignResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetSourceProviderSupport' => __DIR__ .'/GetAssetSourceProviderSupport.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetSourceProviderSupportResponse' => __DIR__ .'/GetAssetSourceProviderSupportResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\AssetSourceProviderSupport' => __DIR__ .'/AssetSourceProviderSupport.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetFolderPath' => __DIR__ .'/GetFolderPath.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetFolderPathResponse' => __DIR__ .'/GetFolderPathResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetProperty' => __DIR__ .'/GetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetPropertyResponse' => __DIR__ .'/GetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetProperties' => __DIR__ .'/GetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetPropertiesResponse' => __DIR__ .'/GetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAllProperties' => __DIR__ .'/GetAllProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAllPropertiesResponse' => __DIR__ .'/GetAllPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetDataSet' => __DIR__ .'/GetDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetDataSetResponse' => __DIR__ .'/GetDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetDataSetResult' => __DIR__ .'/GetDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetXMPTblDataSet' => __DIR__ .'/GetXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetXMPTblDataSetResponse' => __DIR__ .'/GetXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\XMPTblDataSet' => __DIR__ .'/XMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\ArrayOfXMPTbl' => __DIR__ .'/ArrayOfXMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\XMPTbl' => __DIR__ .'/XMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\ArrayOfXMPTblColumn' => __DIR__ .'/ArrayOfXMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\XMPTblColumn' => __DIR__ .'/XMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\ArrayOfXMPTblRow' => __DIR__ .'/ArrayOfXMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\XMPTblRow' => __DIR__ .'/XMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\ArrayOfXMPRowField' => __DIR__ .'/ArrayOfXMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\XMPRowField' => __DIR__ .'/XMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetProperty' => __DIR__ .'/SetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetPropertyResponse' => __DIR__ .'/SetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetProperties' => __DIR__ .'/SetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetPropertiesResponse' => __DIR__ .'/SetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\IsAssetsViewAvailable' => __DIR__ .'/IsAssetsViewAvailable.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\IsAssetsViewAvailableResponse' => __DIR__ .'/IsAssetsViewAvailableResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetSourceType' => __DIR__ .'/GetAssetSourceType.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetSourceTypeResponse' => __DIR__ .'/GetAssetSourceTypeResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetSourceParameters' => __DIR__ .'/GetAssetSourceParameters.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetSourceParametersResponse' => __DIR__ .'/GetAssetSourceParametersResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetAssetSourceParameters' => __DIR__ .'/SetAssetSourceParameters.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetAssetSourceParametersResponse' => __DIR__ .'/SetAssetSourceParametersResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetSourceInfo' => __DIR__ .'/GetAssetSourceInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetSourceInfoResponse' => __DIR__ .'/GetAssetSourceInfoResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\AssetSourceStruct' => __DIR__ .'/AssetSourceStruct.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetSourceInfoEx' => __DIR__ .'/GetAssetSourceInfoEx.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetSourceInfoExResponse' => __DIR__ .'/GetAssetSourceInfoExResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\AssetSourceInfo' => __DIR__ .'/AssetSourceInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetName' => __DIR__ .'/GetName.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetNameResponse' => __DIR__ .'/GetNameResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetName' => __DIR__ .'/SetName.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetNameResponse' => __DIR__ .'/SetNameResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetPriority' => __DIR__ .'/GetPriority.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetPriorityResponse' => __DIR__ .'/GetPriorityResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetPriority' => __DIR__ .'/SetPriority.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetPriorityResponse' => __DIR__ .'/SetPriorityResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetActiveness' => __DIR__ .'/GetActiveness.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetActivenessResponse' => __DIR__ .'/GetActivenessResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetActiveness' => __DIR__ .'/SetActiveness.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetActivenessResponse' => __DIR__ .'/SetActivenessResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetID' => __DIR__ .'/GetAssetID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetIDResponse' => __DIR__ .'/GetAssetIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssets' => __DIR__ .'/GetAssets.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetsResponse' => __DIR__ .'/GetAssetsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetsDataSet' => __DIR__ .'/GetAssetsDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetsDataSetResponse' => __DIR__ .'/GetAssetsDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetsDataSetResult' => __DIR__ .'/GetAssetsDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetsXMPTblDataSet' => __DIR__ .'/GetAssetsXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetAssetsXMPTblDataSetResponse' => __DIR__ .'/GetAssetsXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\DeleteAssets' => __DIR__ .'/DeleteAssets.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\DeleteAssetsResponse' => __DIR__ .'/DeleteAssetsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\DeleteAllAssets' => __DIR__ .'/DeleteAllAssets.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\DeleteAllAssetsResponse' => __DIR__ .'/DeleteAllAssetsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetID' => __DIR__ .'/GetID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetIDResponse' => __DIR__ .'/GetIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\IsExist' => __DIR__ .'/IsExist.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\IsExistResponse' => __DIR__ .'/IsExistResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetSettings' => __DIR__ .'/SetSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\ArrayOfSetting' => __DIR__ .'/ArrayOfSetting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\Setting' => __DIR__ .'/Setting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\SetSettingsResponse' => __DIR__ .'/SetSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetSettings' => __DIR__ .'/GetSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\GetSettingsResponse' => __DIR__ .'/GetSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\DeleteSettings' => __DIR__ .'/DeleteSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_8_2_3\BasicServices\AssetSource_SSP\DeleteSettingsResponse' => __DIR__ .'/DeleteSettingsResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_80370c70de3a1829762360b8eedb3d52');

// Do nothing. The rest is just leftovers from the code generation.
{
}
