<?php


function autoload_e629f80a2a4b5b162a38fde505aebe81($class)
{
    $classes = array(
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\EmailMarketing_SSP' => __DIR__ . '/EmailMarketing_SSP.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\CreateNew' => __DIR__ . '/CreateNew.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ArrayOfProperty' => __DIR__ . '/ArrayOfProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\Property' => __DIR__ . '/Property.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\CreateNewResponse' => __DIR__ . '/CreateNewResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\Replace' => __DIR__ . '/Replace.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ReplaceResponse' => __DIR__ . '/ReplaceResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\Delete' => __DIR__ . '/Delete.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\DeleteResponse' => __DIR__ . '/DeleteResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetProperty' => __DIR__ . '/GetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetPropertyResponse' => __DIR__ . '/GetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetProperties' => __DIR__ . '/GetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ArrayOfString' => __DIR__ . '/ArrayOfString.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetPropertiesResponse' => __DIR__ . '/GetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetAllProperties' => __DIR__ . '/GetAllProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetAllPropertiesResponse' => __DIR__ . '/GetAllPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetDataSet' => __DIR__ . '/GetDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetDataSetResponse' => __DIR__ . '/GetDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetDataSetResult' => __DIR__ . '/GetDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetXMPTblDataSet' => __DIR__ . '/GetXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetXMPTblDataSetResponse' => __DIR__ . '/GetXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\XMPTblDataSet' => __DIR__ . '/XMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ArrayOfXMPTbl' => __DIR__ . '/ArrayOfXMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\XMPTbl' => __DIR__ . '/XMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ArrayOfXMPTblColumn' => __DIR__ . '/ArrayOfXMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\XMPTblColumn' => __DIR__ . '/XMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ArrayOfXMPTblRow' => __DIR__ . '/ArrayOfXMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\XMPTblRow' => __DIR__ . '/XMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ArrayOfXMPRowField' => __DIR__ . '/ArrayOfXMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\XMPRowField' => __DIR__ . '/XMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SetProperty' => __DIR__ . '/SetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SetPropertyResponse' => __DIR__ . '/SetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SetProperties' => __DIR__ . '/SetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SetPropertiesResponse' => __DIR__ . '/SetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetCampaign' => __DIR__ . '/GetCampaign.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetCampaignResponse' => __DIR__ . '/GetCampaignResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetID' => __DIR__ . '/GetID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetIDResponse' => __DIR__ . '/GetIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetLastJob' => __DIR__ . '/GetLastJob.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetLastJobResponse' => __DIR__ . '/GetLastJobResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\Send' => __DIR__ . '/Send.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SendResponse' => __DIR__ . '/SendResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SendMail' => __DIR__ . '/SendMail.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\EmailHeaderInfo' => __DIR__ . '/EmailHeaderInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ArrayOfEmailAddress' => __DIR__ . '/ArrayOfEmailAddress.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\EmailAddress' => __DIR__ . '/EmailAddress.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SendMailResponse' => __DIR__ . '/SendMailResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ArrayOfSendEmailResult' => __DIR__ . '/ArrayOfSendEmailResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SendEmailResult' => __DIR__ . '/SendEmailResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SendMailByPopulation' => __DIR__ . '/SendMailByPopulation.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SendMailByPopulationResponse' => __DIR__ . '/SendMailByPopulationResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SendMailByRun' => __DIR__ . '/SendMailByRun.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SendMailByRunResponse' => __DIR__ . '/SendMailByRunResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetEmailHeader' => __DIR__ . '/GetEmailHeader.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetEmailHeaderResponse' => __DIR__ . '/GetEmailHeaderResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmail' => __DIR__ . '/PreviewEmail.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailResponse' => __DIR__ . '/PreviewEmailResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailByPopulation' => __DIR__ . '/PreviewEmailByPopulation.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailByPopulationResponse' => __DIR__ . '/PreviewEmailByPopulationResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailByRun' => __DIR__ . '/PreviewEmailByRun.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailByRunResponse' => __DIR__ . '/PreviewEmailByRunResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentId' => __DIR__ . '/PreviewEmailDocumentId.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentIdResponse' => __DIR__ . '/PreviewEmailDocumentIdResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailResult' => __DIR__ . '/PreviewEmailResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentIdByPopulation' => __DIR__ . '/PreviewEmailDocumentIdByPopulation.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentIdByPopulationResponse' => __DIR__ . '/PreviewEmailDocumentIdByPopulationResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentIdByRun' => __DIR__ . '/PreviewEmailDocumentIdByRun.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentIdByRunResponse' => __DIR__ . '/PreviewEmailDocumentIdByRunResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocument' => __DIR__ . '/PreviewEmailDocument.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentResponse' => __DIR__ . '/PreviewEmailDocumentResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentByPopulation' => __DIR__ . '/PreviewEmailDocumentByPopulation.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentByPopulationResponse' => __DIR__ . '/PreviewEmailDocumentByPopulationResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentByRun' => __DIR__ . '/PreviewEmailDocumentByRun.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreviewEmailDocumentByRunResponse' => __DIR__ . '/PreviewEmailDocumentByRunResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetPreviewEmailResult' => __DIR__ . '/GetPreviewEmailResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetPreviewEmailResultResponse' => __DIR__ . '/GetPreviewEmailResultResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\Suspend' => __DIR__ . '/Suspend.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SuspendResponse' => __DIR__ . '/SuspendResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\Resume' => __DIR__ . '/Resume.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ResumeResponse' => __DIR__ . '/ResumeResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\IsTracked' => __DIR__ . '/IsTracked.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\IsTrackedResponse' => __DIR__ . '/IsTrackedResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\IsReadyForBatch' => __DIR__ . '/IsReadyForBatch.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\IsReadyForBatchResponse' => __DIR__ . '/IsReadyForBatchResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\IsReadyForOnDemand' => __DIR__ . '/IsReadyForOnDemand.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\IsReadyForOnDemandResponse' => __DIR__ . '/IsReadyForOnDemandResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetCorrespondingJobID' => __DIR__ . '/GetCorrespondingJobID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetCorrespondingJobIDResponse' => __DIR__ . '/GetCorrespondingJobIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SendSplitted' => __DIR__ . '/SendSplitted.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SendSplittedResponse' => __DIR__ . '/SendSplittedResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\Test' => __DIR__ . '/Test.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\TestResponse' => __DIR__ . '/TestResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\Preflight' => __DIR__ . '/Preflight.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreflightResponse' => __DIR__ . '/PreflightResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreflightSplitted' => __DIR__ . '/PreflightSplitted.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\PreflightSplittedResponse' => __DIR__ . '/PreflightSplittedResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\IsExist' => __DIR__ . '/IsExist.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\IsExistResponse' => __DIR__ . '/IsExistResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SetSettings' => __DIR__ . '/SetSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\ArrayOfSetting' => __DIR__ . '/ArrayOfSetting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\Setting' => __DIR__ . '/Setting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\SetSettingsResponse' => __DIR__ . '/SetSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetSettings' => __DIR__ . '/GetSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\GetSettingsResponse' => __DIR__ . '/GetSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\DeleteSettings' => __DIR__ . '/DeleteSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_9_8_2\OtherServices\EmailMarketing_SSP\DeleteSettingsResponse' => __DIR__ . '/DeleteSettingsResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    }
}

spl_autoload_register('autoload_e629f80a2a4b5b162a38fde505aebe81');

// Do nothing. The rest is just leftovers from the code generation.
{
}
