<?php


 function autoload_a49c8e90274ccb864635bddfe5fb6428($class)
{
    $classes = array(
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\Font_SSP' => __DIR__ .'/Font_SSP.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\CreateNew' => __DIR__ .'/CreateNew.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\ArrayOfProperty' => __DIR__ .'/ArrayOfProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\Property' => __DIR__ .'/Property.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\CreateNewResponse' => __DIR__ .'/CreateNewResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\CreateNewFromZip' => __DIR__ .'/CreateNewFromZip.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\CreateNewFromZipResponse' => __DIR__ .'/CreateNewFromZipResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\Replace' => __DIR__ .'/Replace.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\ReplaceResponse' => __DIR__ .'/ReplaceResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\Delete' => __DIR__ .'/Delete.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\DeleteResponse' => __DIR__ .'/DeleteResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetCampaign' => __DIR__ .'/GetCampaign.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetCampaignResponse' => __DIR__ .'/GetCampaignResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetProperty' => __DIR__ .'/GetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetPropertyResponse' => __DIR__ .'/GetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetModificationDate' => __DIR__ .'/GetModificationDate.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetModificationDateResponse' => __DIR__ .'/GetModificationDateResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetProperties' => __DIR__ .'/GetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetPropertiesResponse' => __DIR__ .'/GetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetAllProperties' => __DIR__ .'/GetAllProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetAllPropertiesResponse' => __DIR__ .'/GetAllPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetDataSet' => __DIR__ .'/GetDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetDataSetResponse' => __DIR__ .'/GetDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetDataSetResult' => __DIR__ .'/GetDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetXMPTblDataSet' => __DIR__ .'/GetXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetXMPTblDataSetResponse' => __DIR__ .'/GetXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\XMPTblDataSet' => __DIR__ .'/XMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\ArrayOfXMPTbl' => __DIR__ .'/ArrayOfXMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\XMPTbl' => __DIR__ .'/XMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\ArrayOfXMPTblColumn' => __DIR__ .'/ArrayOfXMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\XMPTblColumn' => __DIR__ .'/XMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\ArrayOfXMPTblRow' => __DIR__ .'/ArrayOfXMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\XMPTblRow' => __DIR__ .'/XMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\ArrayOfXMPRowField' => __DIR__ .'/ArrayOfXMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\XMPRowField' => __DIR__ .'/XMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\SetProperty' => __DIR__ .'/SetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\SetPropertyResponse' => __DIR__ .'/SetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\SetProperties' => __DIR__ .'/SetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\SetPropertiesResponse' => __DIR__ .'/SetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetName' => __DIR__ .'/GetName.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetNameResponse' => __DIR__ .'/GetNameResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetPath' => __DIR__ .'/GetPath.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetPathResponse' => __DIR__ .'/GetPathResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSecondaryPath' => __DIR__ .'/GetSecondaryPath.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSecondaryPathResponse' => __DIR__ .'/GetSecondaryPathResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinaryFileStream' => __DIR__ .'/GetBinaryFileStream.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinaryFileStreamResponse' => __DIR__ .'/GetBinaryFileStreamResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinarySecondaryFileStream' => __DIR__ .'/GetBinarySecondaryFileStream.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinarySecondaryFileStreamResponse' => __DIR__ .'/GetBinarySecondaryFileStreamResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinaryFileStreamChunk' => __DIR__ .'/GetBinaryFileStreamChunk.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinaryFileStreamChunkResponse' => __DIR__ .'/GetBinaryFileStreamChunkResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinarySecondaryFileStreamChunk' => __DIR__ .'/GetBinarySecondaryFileStreamChunk.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinarySecondaryFileStreamChunkResponse' => __DIR__ .'/GetBinarySecondaryFileStreamChunkResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinaryFileStreamSize' => __DIR__ .'/GetBinaryFileStreamSize.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinaryFileStreamSizeResponse' => __DIR__ .'/GetBinaryFileStreamSizeResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinarySecondaryFileStreamSize' => __DIR__ .'/GetBinarySecondaryFileStreamSize.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetBinarySecondaryFileStreamSizeResponse' => __DIR__ .'/GetBinarySecondaryFileStreamSizeResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetFontFileInfo' => __DIR__ .'/GetFontFileInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetFontFileInfoResponse' => __DIR__ .'/GetFontFileInfoResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\FontInfo' => __DIR__ .'/FontInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetFontFileSizeInfo' => __DIR__ .'/GetFontFileSizeInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetFontFileSizeInfoResponse' => __DIR__ .'/GetFontFileSizeInfoResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\FontSizeInfo' => __DIR__ .'/FontSizeInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetUEditCompatibleFileStream' => __DIR__ .'/GetUEditCompatibleFileStream.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetUEditCompatibleFileStreamResponse' => __DIR__ .'/GetUEditCompatibleFileStreamResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFontFileStream' => __DIR__ .'/GetSWFFontFileStream.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFontFileStreamResponse' => __DIR__ .'/GetSWFFontFileStreamResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFileStream' => __DIR__ .'/GetSWFFileStream.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFileStreamResponse' => __DIR__ .'/GetSWFFileStreamResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetFontFamilyAndStyle' => __DIR__ .'/GetFontFamilyAndStyle.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetFontFamilyAndStyleResponse' => __DIR__ .'/GetFontFamilyAndStyleResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetDownloadURL' => __DIR__ .'/GetDownloadURL.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetDownloadURLResponse' => __DIR__ .'/GetDownloadURLResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetID' => __DIR__ .'/GetID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetIDResponse' => __DIR__ .'/GetIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFullNameFontStream' => __DIR__ .'/GetSWFFullNameFontStream.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFullNameFontStreamResponse' => __DIR__ .'/GetSWFFullNameFontStreamResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFullNameFontFamilyAndFace' => __DIR__ .'/GetSWFFullNameFontFamilyAndFace.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFullNameFontFamilyAndFaceResponse' => __DIR__ .'/GetSWFFullNameFontFamilyAndFaceResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFullNameFontStreamWithFamilyAndFace' => __DIR__ .'/GetSWFFullNameFontStreamWithFamilyAndFace.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFullNameFontStreamWithFamilyAndFaceResponse' => __DIR__ .'/GetSWFFullNameFontStreamWithFamilyAndFaceResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFontVersion' => __DIR__ .'/GetSWFFontVersion.php',
        'XMPieWsdlClient\XMPie\uProduce\v_12_2\BasicServices\Font_SSP\GetSWFFontVersionResponse' => __DIR__ .'/GetSWFFontVersionResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_a49c8e90274ccb864635bddfe5fb6428');

// Do nothing. The rest is just leftovers from the code generation.
{
}
