<?php


 function autoload_3f8db5acffb5f233b223392e90864c60($class)
{
    $classes = array(
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\InteractiveCampaign_SSP' => __DIR__ .'/InteractiveCampaign_SSP.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\CreateNew' => __DIR__ .'/CreateNew.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\CreateNewResponse' => __DIR__ .'/CreateNewResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\CreateNewWithProperties' => __DIR__ .'/CreateNewWithProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfProperty' => __DIR__ .'/ArrayOfProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\Property' => __DIR__ .'/Property.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\CreateNewWithPropertiesResponse' => __DIR__ .'/CreateNewWithPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\Replace' => __DIR__ .'/Replace.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ReplaceResponse' => __DIR__ .'/ReplaceResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\Delete' => __DIR__ .'/Delete.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\DeleteResponse' => __DIR__ .'/DeleteResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\Suspend' => __DIR__ .'/Suspend.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\SuspendResponse' => __DIR__ .'/SuspendResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\Resume' => __DIR__ .'/Resume.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ResumeResponse' => __DIR__ .'/ResumeResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\IsExist' => __DIR__ .'/IsExist.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\IsExistResponse' => __DIR__ .'/IsExistResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\IsExistByID' => __DIR__ .'/IsExistByID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\IsExistByIDResponse' => __DIR__ .'/IsExistByIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\Get' => __DIR__ .'/Get.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetResponse' => __DIR__ .'/GetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetResult' => __DIR__ .'/GetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetXMPTblDataSet' => __DIR__ .'/GetXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetXMPTblDataSetResponse' => __DIR__ .'/GetXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\XMPTblDataSet' => __DIR__ .'/XMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfXMPTbl' => __DIR__ .'/ArrayOfXMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\XMPTbl' => __DIR__ .'/XMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfXMPTblColumn' => __DIR__ .'/ArrayOfXMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\XMPTblColumn' => __DIR__ .'/XMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfXMPTblRow' => __DIR__ .'/ArrayOfXMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\XMPTblRow' => __DIR__ .'/XMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfXMPRowField' => __DIR__ .'/ArrayOfXMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\XMPRowField' => __DIR__ .'/XMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORs' => __DIR__ .'/GetADORs.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsResponse' => __DIR__ .'/GetADORsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfPlanObject' => __DIR__ .'/ArrayOfPlanObject.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\PlanObject' => __DIR__ .'/PlanObject.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsDataSet' => __DIR__ .'/GetADORsDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsDataSetResponse' => __DIR__ .'/GetADORsDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsDataSetResult' => __DIR__ .'/GetADORsDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADOR' => __DIR__ .'/GetADOR.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORResponse' => __DIR__ .'/GetADORResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORDataSet' => __DIR__ .'/GetADORDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORDataSetResponse' => __DIR__ .'/GetADORDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORDataSetResult' => __DIR__ .'/GetADORDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetTabularADORColumn' => __DIR__ .'/GetTabularADORColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetTabularADORColumnResponse' => __DIR__ .'/GetTabularADORColumnResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\PlanTabularColumn' => __DIR__ .'/PlanTabularColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetTabularADORColumnDataSet' => __DIR__ .'/GetTabularADORColumnDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetTabularADORColumnDataSetResponse' => __DIR__ .'/GetTabularADORColumnDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetTabularADORColumnDataSetResult' => __DIR__ .'/GetTabularADORColumnDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetTabularADORColumns' => __DIR__ .'/GetTabularADORColumns.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetTabularADORColumnsResponse' => __DIR__ .'/GetTabularADORColumnsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfPlanTabularColumn' => __DIR__ .'/ArrayOfPlanTabularColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetTabularADORColumnsDataSet' => __DIR__ .'/GetTabularADORColumnsDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetTabularADORColumnsDataSetResponse' => __DIR__ .'/GetTabularADORColumnsDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetTabularADORColumnsDataSetResult' => __DIR__ .'/GetTabularADORColumnsDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsValuesForRecipientsXMPDataSet' => __DIR__ .'/GetADORsValuesForRecipientsXMPDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsValuesForRecipientsXMPDataSetResponse' => __DIR__ .'/GetADORsValuesForRecipientsXMPDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsValuesForRecipients' => __DIR__ .'/GetADORsValuesForRecipients.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsValuesForRecipientsResponse' => __DIR__ .'/GetADORsValuesForRecipientsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsValuesForRecipientsResult' => __DIR__ .'/GetADORsValuesForRecipientsResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetRecipientsCount' => __DIR__ .'/GetRecipientsCount.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetRecipientsCountResponse' => __DIR__ .'/GetRecipientsCountResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsValuesForRangeXMPDataSet' => __DIR__ .'/GetADORsValuesForRangeXMPDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsValuesForRangeXMPDataSetResponse' => __DIR__ .'/GetADORsValuesForRangeXMPDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsValuesForRange' => __DIR__ .'/GetADORsValuesForRange.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsValuesForRangeResponse' => __DIR__ .'/GetADORsValuesForRangeResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetADORsValuesForRangeResult' => __DIR__ .'/GetADORsValuesForRangeResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\UpdateADORsValuesForRecipient' => __DIR__ .'/UpdateADORsValuesForRecipient.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\UpdateADORsValuesForRecipientResponse' => __DIR__ .'/UpdateADORsValuesForRecipientResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\InsertADORsValuesForRecipient' => __DIR__ .'/InsertADORsValuesForRecipient.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\InsertADORsValuesForRecipientResponse' => __DIR__ .'/InsertADORsValuesForRecipientResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\DeleteRecipient' => __DIR__ .'/DeleteRecipient.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\DeleteRecipientResponse' => __DIR__ .'/DeleteRecipientResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\AddTrackEvent' => __DIR__ .'/AddTrackEvent.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\XMPDateTime' => __DIR__ .'/XMPDateTime.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\AddTrackEventResponse' => __DIR__ .'/AddTrackEventResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\SendMail' => __DIR__ .'/SendMail.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\EmailHeaderInfo' => __DIR__ .'/EmailHeaderInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfEmailAddress' => __DIR__ .'/ArrayOfEmailAddress.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\EmailAddress' => __DIR__ .'/EmailAddress.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfEmailBodyOptions' => __DIR__ .'/ArrayOfEmailBodyOptions.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\EmailBodyOptions' => __DIR__ .'/EmailBodyOptions.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\SendMailResponse' => __DIR__ .'/SendMailResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfSendEmailResult' => __DIR__ .'/ArrayOfSendEmailResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\SendEmailResult' => __DIR__ .'/SendEmailResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetCorespondingJobIDAsString' => __DIR__ .'/GetCorespondingJobIDAsString.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetCorespondingJobIDAsStringResponse' => __DIR__ .'/GetCorespondingJobIDAsStringResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetCorespondingJobID' => __DIR__ .'/GetCorespondingJobID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetCorespondingJobIDResponse' => __DIR__ .'/GetCorespondingJobIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetDataSetByID' => __DIR__ .'/GetDataSetByID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetDataSetByIDResponse' => __DIR__ .'/GetDataSetByIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetDataSetByIDResult' => __DIR__ .'/GetDataSetByIDResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetXMPTblDataSetByID' => __DIR__ .'/GetXMPTblDataSetByID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetXMPTblDataSetByIDResponse' => __DIR__ .'/GetXMPTblDataSetByIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\SetSettingsByID' => __DIR__ .'/SetSettingsByID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\ArrayOfSetting' => __DIR__ .'/ArrayOfSetting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\Setting' => __DIR__ .'/Setting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\SetSettingsByIDResponse' => __DIR__ .'/SetSettingsByIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetSettingsByID' => __DIR__ .'/GetSettingsByID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetSettingsByIDResponse' => __DIR__ .'/GetSettingsByIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\DeleteSettingsByID' => __DIR__ .'/DeleteSettingsByID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\DeleteSettingsByIDResponse' => __DIR__ .'/DeleteSettingsByIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetStatusByID' => __DIR__ .'/GetStatusByID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetStatusByIDResponse' => __DIR__ .'/GetStatusByIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\StatusInfo' => __DIR__ .'/StatusInfo.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\IsTracked' => __DIR__ .'/IsTracked.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\IsTrackedResponse' => __DIR__ .'/IsTrackedResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetID' => __DIR__ .'/GetID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetIDResponse' => __DIR__ .'/GetIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetName' => __DIR__ .'/GetName.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetNameResponse' => __DIR__ .'/GetNameResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\IsAdaptedToWeb' => __DIR__ .'/IsAdaptedToWeb.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\IsAdaptedToWebResponse' => __DIR__ .'/IsAdaptedToWebResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\SetPropertyByID' => __DIR__ .'/SetPropertyByID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\SetPropertyByIDResponse' => __DIR__ .'/SetPropertyByIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetPropertyByID' => __DIR__ .'/GetPropertyByID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_10_2_1\OtherServices\InteractiveCampaign_SSP\GetPropertyByIDResponse' => __DIR__ .'/GetPropertyByIDResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_3f8db5acffb5f233b223392e90864c60');

// Do nothing. The rest is just leftovers from the code generation.
{
}
