<?php


 function autoload_f7c937d951dafdbe68dfda9e6cde42c4($class)
{
    $classes = array(
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\Account_SSP' => __DIR__ .'/Account_SSP.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\CreateNew' => __DIR__ .'/CreateNew.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\ArrayOfProperty' => __DIR__ .'/ArrayOfProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\Property' => __DIR__ .'/Property.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\CreateNewResponse' => __DIR__ .'/CreateNewResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\Delete' => __DIR__ .'/Delete.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteResponse' => __DIR__ .'/DeleteResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCustomer' => __DIR__ .'/GetCustomer.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCustomerResponse' => __DIR__ .'/GetCustomerResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetFolderPath' => __DIR__ .'/GetFolderPath.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetFolderPathResponse' => __DIR__ .'/GetFolderPathResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetName' => __DIR__ .'/GetName.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetNameResponse' => __DIR__ .'/GetNameResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetProperty' => __DIR__ .'/GetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetPropertyResponse' => __DIR__ .'/GetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetProperties' => __DIR__ .'/GetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetPropertiesResponse' => __DIR__ .'/GetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAllProperties' => __DIR__ .'/GetAllProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAllPropertiesResponse' => __DIR__ .'/GetAllPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetDataSet' => __DIR__ .'/GetDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetDataSetResponse' => __DIR__ .'/GetDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetDataSetResult' => __DIR__ .'/GetDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetXMPTblDataSet' => __DIR__ .'/GetXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetXMPTblDataSetResponse' => __DIR__ .'/GetXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\XMPTblDataSet' => __DIR__ .'/XMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\ArrayOfXMPTbl' => __DIR__ .'/ArrayOfXMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\XMPTbl' => __DIR__ .'/XMPTbl.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\ArrayOfXMPTblColumn' => __DIR__ .'/ArrayOfXMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\XMPTblColumn' => __DIR__ .'/XMPTblColumn.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\ArrayOfXMPTblRow' => __DIR__ .'/ArrayOfXMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\XMPTblRow' => __DIR__ .'/XMPTblRow.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\ArrayOfXMPRowField' => __DIR__ .'/ArrayOfXMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\XMPRowField' => __DIR__ .'/XMPRowField.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\SetProperty' => __DIR__ .'/SetProperty.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\SetPropertyResponse' => __DIR__ .'/SetPropertyResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\SetProperties' => __DIR__ .'/SetProperties.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\SetPropertiesResponse' => __DIR__ .'/SetPropertiesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCampaignID' => __DIR__ .'/GetCampaignID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCampaignIDResponse' => __DIR__ .'/GetCampaignIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCampaigns' => __DIR__ .'/GetCampaigns.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCampaignsResponse' => __DIR__ .'/GetCampaignsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCampaignsDataSet' => __DIR__ .'/GetCampaignsDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCampaignsDataSetResponse' => __DIR__ .'/GetCampaignsDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCampaignsDataSetResult' => __DIR__ .'/GetCampaignsDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCampaignsXMPTblDataSet' => __DIR__ .'/GetCampaignsXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetCampaignsXMPTblDataSetResponse' => __DIR__ .'/GetCampaignsXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteCampaigns' => __DIR__ .'/DeleteCampaigns.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteCampaignsResponse' => __DIR__ .'/DeleteCampaignsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteAllCampaigns' => __DIR__ .'/DeleteAllCampaigns.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteAllCampaignsResponse' => __DIR__ .'/DeleteAllCampaignsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetID' => __DIR__ .'/GetID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetIDResponse' => __DIR__ .'/GetIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\IsExist' => __DIR__ .'/IsExist.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\IsExistResponse' => __DIR__ .'/IsExistResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\SetSettings' => __DIR__ .'/SetSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\ArrayOfSetting' => __DIR__ .'/ArrayOfSetting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\Setting' => __DIR__ .'/Setting.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\SetSettingsResponse' => __DIR__ .'/SetSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetSettings' => __DIR__ .'/GetSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetSettingsResponse' => __DIR__ .'/GetSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteSettings' => __DIR__ .'/DeleteSettings.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteSettingsResponse' => __DIR__ .'/DeleteSettingsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetADORs' => __DIR__ .'/GetADORs.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetADORsResponse' => __DIR__ .'/GetADORsResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\ArrayOfPlanObject' => __DIR__ .'/ArrayOfPlanObject.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\PlanObject' => __DIR__ .'/PlanObject.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAccountDataSourceID' => __DIR__ .'/GetAccountDataSourceID.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAccountDataSourceIDResponse' => __DIR__ .'/GetAccountDataSourceIDResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAccountDataSources' => __DIR__ .'/GetAccountDataSources.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAccountDataSourcesResponse' => __DIR__ .'/GetAccountDataSourcesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAccountDataSourcesDataSet' => __DIR__ .'/GetAccountDataSourcesDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAccountDataSourcesDataSetResponse' => __DIR__ .'/GetAccountDataSourcesDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAccountDataSourcesDataSetResult' => __DIR__ .'/GetAccountDataSourcesDataSetResult.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAccountDataSourcesXMPTblDataSet' => __DIR__ .'/GetAccountDataSourcesXMPTblDataSet.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\GetAccountDataSourcesXMPTblDataSetResponse' => __DIR__ .'/GetAccountDataSourcesXMPTblDataSetResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteAccountDataSources' => __DIR__ .'/DeleteAccountDataSources.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteAccountDataSourcesResponse' => __DIR__ .'/DeleteAccountDataSourcesResponse.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteAllAccountDataSources' => __DIR__ .'/DeleteAllAccountDataSources.php',
        'XMPieWsdlClient\XMPie\uProduce\v_13_2\BasicServices\Account_SSP\DeleteAllAccountDataSourcesResponse' => __DIR__ .'/DeleteAllAccountDataSourcesResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_f7c937d951dafdbe68dfda9e6cde42c4');

// Do nothing. The rest is just leftovers from the code generation.
{
}
